---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: Alfatangos
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/bluefin:stable
image-version: latest # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: dnf
    repos:
       nonfree: rpmfusion
       cleanup: true
    install:
      packages:
        - akmod-nvidia-580xx
        - xorg-x11-drv-nvidia-580xx
        - xorg-x11-drv-nvidia-580xx-libs
        - xorg-x11-drv-nvidia-580xx-cuda
        - xorg-x11-drv-nvidia-580xx-cuda-libs
        - xorg-x11-drv-nvidia-580xx-libs.i686
        - libva-nvidia-driver
        - libva-nvidia-driver.i686
        - libva-utils
        - vdpauinfo
        - vulkan
        - vulkan-loader
        - vulkan-tools
        - vulkan-loader-i686

    remove:
      packages:
        # example: removing firefox (in favor of the flatpak)
        # "firefox" is the main package, "firefox-langpacks" is a dependency
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: default-flatpaks
    configurations:
      - notify: true # Send notification after install/uninstall is finished (true/false)
        scope: system
        # If no repo information is specified, Flathub will be used by default
        install: # system flatpaks we want all users to have and not remove
          - org.mozilla.firefox
          # - org.gnome.Loupe
      - scope: user # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: containerfile
    snippets:
      - |
        # Inietta le variabili d'ambiente in /etc/environment dentro l'immagine OCI
        echo "MOZ_DISABLE_RDD_SANDBOX=1" >> /etc/environment
        echo "LIBVA_DRIVER_NAME=nvidia" >> /etc/environment
        echo "__GLX_VENDOR_LIBRARY_NAME=nvidia" >> /etc/environment
        
        # Opzionale: Forza Firefox a usare Wayland nativamente se usi Wayland
        echo "MOZ_ENABLE_WAYLAND=1" >> /etc/environment
  - type: kargs
    kargs:
      - rd.driver.blacklist=nouveau
      - modprobe.blacklist=nouveau
      - nvidia-drm.modeset=1
