---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: alfatangos
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bluefin
image-version: latest

modules:
  - type: files
    files:
      - source: system
        destination: / 

  #- type: rpm-ostree
  #  remove:
  #    - firefox
  #    - firefox-langpacks

  # Modulo DNF pulito solo per installare i driver
- type: containerfile
    snippets:
     - RUN rpm -Uvh --nodeps https://mirrors.rpmfusion.org/free/fedora/rpmfusion-free-release-$(rpm -E %fedora).noarch.rpm https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm

  - type: dnf
    repos:
      nonfree: rpmfusion
      cleanup: true
    install:
      packages:
        # Driver Core Nvidia Legacy 580xx
        - akmod-nvidia-580xx
        - xorg-x11-drv-nvidia-580xx
        - xorg-x11-drv-nvidia-580xx-libs
        - xorg-x11-drv-nvidia-580xx-cuda
        - xorg-x11-drv-nvidia-580xx-cuda-libs
        
        # Librerie 32-bit per Gaming (Steam/Wine)
        - xorg-x11-drv-nvidia-580xx-libs.i686
        - libva-nvidia-driver.i686
        - vulkan-loader.i686
        
        # Accelerazione Video VA-API/VDPAU
        - libva-nvidia-driver
        - libva-utils
        - vdpauinfo
        
        # Supporto Vulkan
        - vulkan-loader
        - vulkan-tools

  - type: default-flatpaks
    configurations:
      - notify: true 
        scope: system
        install: 
          - org.mozilla.firefox
      - scope: user 

  - type: signing 

  - type: containerfile
    snippets:
      - |
        RUN echo "MOZ_DISABLE_RDD_SANDBOX=1" >> /etc/environment
        RUN echo "LIBVA_DRIVER_NAME=nvidia" >> /etc/environment
        RUN echo "__GLX_VENDOR_LIBRARY_NAME=nvidia" >> /etc/environment
        RUN echo "MOZ_ENABLE_WAYLAND=1" >> /etc/environment

  - type: kargs
    kargs:
      - rd.driver.blacklist=nouveau
      - modprobe.blacklist=nouveau
      - nvidia-drm.modeset=1
